# Generated by Django 2.2.3 on 2019-07-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeSpan', models.IntegerField(default=0)),
                ('SuperData', models.ForeignKey(on_delete='PROTECT', to='project.Datainfo')),
            ],
        ),
    ]
