# Generated by Django 2.2.3 on 2019-07-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_subdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdata',
            name='Name',
            field=models.CharField(default='TEMP', max_length=200),
            preserve_default=False,
        ),
    ]
