# Generated by Django 2.2.3 on 2019-07-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_subdata_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdata',
            name='Nodes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subdata',
            name='Static_Edges',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subdata',
            name='Temporal_Edges',
            field=models.IntegerField(default=0),
        ),
    ]
