# Generated by Django 2.2.3 on 2019-08-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20190731_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datainfo',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
