# Generated by Django 2.2.3 on 2019-10-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20190801_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdata',
            name='dataspace',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subdata',
            name='heatmap',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
