# Generated by Django 2.2.3 on 2019-10-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_graphinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphinfo',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
