# Generated by Django 2.2.3 on 2019-10-25 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20191024_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdata',
            name='total_communities',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
