# Generated by Django 2.2.3 on 2020-02-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_subdata_total_communities'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdata',
            name='force_links',
            field=models.TextField(default='...'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subdata',
            name='force_nodes',
            field=models.TextField(default='...'),
            preserve_default=False,
        ),
    ]
