# Generated by Django 2.2.3 on 2020-02-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20200209_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdata',
            name='communities',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subdata',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
