# Generated by Django 2.2.3 on 2020-02-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20200209_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdata',
            name='distribution',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
