# Generated by Django 2.2.3 on 2020-02-10 10:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_auto_20200210_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdata',
            name='max_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='subdata',
            name='min_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
