# Generated by Django 2.2.3 on 2020-03-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_otherdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherdata',
            name='TimeSpan',
            field=models.CharField(max_length=200),
        ),
    ]
