# Generated by Django 2.2.3 on 2020-03-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_auto_20200310_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherdata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
