# Generated by Django 2.2.3 on 2020-03-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_auto_20200310_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherdata',
            name='prediction',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='subdata',
            name='prediction',
            field=models.TextField(default=''),
        ),
    ]
