# Generated by Django 2.2.3 on 2020-04-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_otherdata_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherdata',
            name='Static_Edges',
        ),
        migrations.RemoveField(
            model_name='otherdata',
            name='Temporal_Edges',
        ),
        migrations.AddField(
            model_name='otherdata',
            name='Edges',
            field=models.IntegerField(default=0),
        ),
    ]
