# Generated by Django 2.2.3 on 2020-04-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_auto_20200404_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherdata',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
