# Generated by Django 2.2.3 on 2020-04-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0025_auto_20200404_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherdata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
